### ISSUE TITLE
Question: How often do new releases get shipped to PyPI?

### ISSUE THREAD

**Issue by safetymonkey** [GoogleCloudPlatform/cloud-profiler-python#61]
I'm interested in integrating this library with one of my projects but there's a dependency conflict in version 2.0.3. I see a fix was checked in 9 days ago that will resolve the conflict and has bumped the version to 2.0.4, but it's not clear when it will go out. Thanks for your help!

**Comment by kalyanac** [comment]
Thanks for filing this. I just triggered a release build. It should be available shortly.

**Comment by jqll** [comment]
Thanks for filing this. 2.0.4 has been released. To answer the question, I discussed with kalyanac@ and we agreed that we should release right after a new version is merged. I'll update the team doc.
