### ISSUE TITLE
Error starting the profiler

### ISSUE THREAD

**Issue by Sancer** [GoogleCloudPlatform/cloud-profiler-python#67]
When I try to start the profiler I see the following log message:

> Failed to build the Discovery client for profiler (will retry after 634.737s): 'ClientOptions' object has no attribute 'credentials_file'

**Environment details**
GAE standard python37 runtime:
Python version: 3.7
google-cloud-profiler==2.0.4
gunicorn==20.0.4

**Code example**

```python
 googlecloudprofiler.start(
            service=self._config.service_name,
            verbose=self._config.verbose,
            service_version=self._config.service_version,
            project_id=self._config.project_id,
            service_account_json_file=self._config.service_account_json_file)
```

- I tried to fix it by forcing the version to `google-cloud-core==1.3.0` but I was unlucky
- I tried to call the start method without parameters as in the documentation, but it gives similar problems

**Comment by kalyanac** [comment]
#66 seems related. Were there any error or warning messages during installation of dependencies?

**Comment by Sancer** [comment]
> #66 seems related. Were there any error or warning messages during installation of dependencies?

No error or warning message appears during pip installation

**Comment by kalyanac** [comment]
I see `cloud-pubsub-1.2.0` is getting installed. As per discussion in #66, this issue is only fixed when google-cloud-pubsub is upgraded to 1.6.0 or greater.

**Comment by Sancer** [comment]
Thank you very much for your help 😄 . Uploading the pubsub version has been solved
